# Generated by Django 4.2.17 on 2024-12-22 08:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='badges/')),
                ('requirement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('SCIENTIST', 'Scientist'), ('VOLUNTEER', 'Patient Volunteer')], max_length=20)),
                ('ability_description', models.TextField()),
                ('recruitment_bonus', models.IntegerField(default=0)),
                ('data_analysis_bonus', models.IntegerField(default=0)),
                ('patient_care_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_participants', models.IntegerField()),
                ('current_participants', models.IntegerField(default=0)),
                ('budget_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning Phase'), ('RECRUITING', 'Recruiting'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PLANNING', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('success_rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_points', models.IntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('reputation', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('research_points', models.IntegerField(default=0)),
                ('research_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.character')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('multiplier_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('recruitment_bonus', models.IntegerField(default=0)),
                ('analysis_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StoryChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_level', models.IntegerField(default=1)),
                ('required_reputation', models.IntegerField(default=0)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_participants', models.IntegerField()),
                ('min_success_rate', models.IntegerField()),
                ('reward_xp', models.IntegerField()),
                ('reward_reputation', models.IntegerField()),
                ('reward_research_points', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.storychapter')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.badge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PatientStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('CANCER', 'Cancer Treatment'), ('RARE', 'Rare Disease'), ('CHRONIC', 'Chronic Condition'), ('MENTAL', 'Mental Health'), ('VACCINE', 'Vaccine Trial')], max_length=20)),
                ('background', models.TextField()),
                ('motivation', models.TextField()),
                ('success_outcome', models.TextField()),
                ('failure_outcome', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.storychapter')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('condition', models.CharField(max_length=100)),
                ('is_placebo', models.BooleanField(default=False)),
                ('dropout_risk', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('satisfaction', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.clinicaltrial')),
            ],
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile'),
        ),
        migrations.CreateModel(
            name='StoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.storychapter')),
                ('current_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.patientstory')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
            options={
                'unique_together': {('player', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='PlayerUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.researchupgrade')),
            ],
            options={
                'unique_together': {('player', 'upgrade')},
            },
        ),
    ]
